# Generated by Django 5.1.1 on 2025-02-21 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=0)),
                (
                    "furniture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.furniture"
                    ),
                ),
            ],
        ),
    ]
